# Use the official PostgreSQL image as a parent image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB=postgres
ENV POSTGRES_USER=email
ENV POSTGRES_PASSWORD=Email@2023
ENV PGPORT=5433

# Expose the custom port
EXPOSE 5433
